---
- name: install haproxy
  hosts: loadbalancer
  become: true
  
  tasks:
    - name: Update and upgrade apt packages
      apt:
       update_cache: yes
       upgrade: "yes" 
     
    - name: Install UFW
      apt:
       name: ufw
       state: present
    - name: Setup rules
      command: "{{ item }}"
      with_items:
        - ufw default deny incoming
        - ufw allow ssh
        - ufw allow https
        - ufw --force enable
           
    - name: install haproxy
      apt:
       name: haproxy
       state: present

    - name: Copy ha-proxy configuration file
      template:
       src: haproxy.cfg
       dest: "/etc/haproxy/haproxy.cfg"

    - name: "start service of haproxy"
      service:
       name: "haproxy"
       state: restarted
